### ISSUE TITLE
Question. Could this Blake3 wrapper be used in .Net Core?

### ISSUE THREAD

**Issue by dlandi** [BigOyayubi/BLAKE3Unity#1]
Question. Could this Blake3 wrapper be used in .Net Core?

**Comment by BigOyayubi** [comment]
@dlandi 
Thank you for your question.

Sorry, I have never tried to use Blake3 wrapper in .Net Core.
But I think Blake3 wrapper could be used in .Net Core with DllImport Attribute.

* source
     * https://github.com/BigOyayubi/BLAKE3Unity/blob/a86e711de4424d02b94e8a992914dc2fb176f6d2/unity-sample/Assets/Scripts/Bindings.cs#L179
* .net core documents
    * https://docs.microsoft.com/ja-jp/dotnet/standard/native-interop/pinvoke

**Comment by dlandi** [comment]
Thanks

**Comment by BigOyayubi** [comment]
@dlandi 
Hi. I test above your question. https://github.com/BigOyayubi/DotNetBlake3
is this useful for you ?

**Comment by dlandi** [comment]
Hi. Want do you mean? Did you test your project on .NET Core?

**Comment by BigOyayubi** [comment]
yes i did (maybe)
DotNetBlake3 uses .NetStandard2.0.
You can use Blake3 wrapper on .NET Core Project.
i tested DotNetBlake3 on Ubuntu.
if you want to use it other platform, you have to run "cargo build" for other platform.

**Comment by dlandi** [comment]
OK. Thanks
